#pragma once


#define SKIV_CLI_MAJOR 0
#define SKIV_CLI_MINOR 0
#define SKIV_CLI_BUILD 4
#define SKIV_CLI_REV   0

#define _A2(a)     #a
#define  _A(a)  _A2(a)
#define _L2(w)  L ## w
#define  _L(w) _L2(w)


#if SKIV_CLI_REV > 0
#define SKIV_CLI_VERSION_STR_A    _A(SKIV_CLI_MAJOR) "." _A(SKIV_CLI_MINOR) "." _A(SKIV_CLI_BUILD) "." _A(SKIV_CLI_REV)
#else
#define SKIV_CLI_VERSION_STR_A    _A(SKIV_CLI_MAJOR) "." _A(SKIV_CLI_MINOR) "." _A(SKIV_CLI_BUILD)
#endif

#define SKIV_CLI_VERSION_STR_W _L(SKIV_CLI_VERSION_STR_A)


#define SKIV_CLI_FILE_VERSION     SKIV_CLI_MAJOR,SKIV_CLI_MINOR,SKIV_CLI_BUILD,SKIV_CLI_REV
#define SKIV_CLI_PRODUCT_VERSION  SKIV_CLI_MAJOR,SKIV_CLI_MINOR,SKIV_CLI_BUILD,SKIV_CLI_REV


#define SKIV_CLI_WINDOW_TITLE_A          "SKIV CLI Tool"
#define SKIV_CLI_WINDOW_TITLE_W       _L("SKIV CLI Tool")
#define SKIV_CLI_WINDOW_TITLE             SKIV_CLI_WINDOW_TITLE_W
#define SKIV_CLI_WINDOW_TITLE_SHORT_A    "SKIV CLI"
#define SKIV_CLI_WINDOW_TITLE_SHORT_W _L("SKIV CLI")
#define SKIV_CLI_WINDOW_TITLE_SHORT       SKIV_CLI_WINDOW_TITLE_SHORT_W
#define SKIV_CLI_WINDOW_HASH          "###SKIV CLI Tool"
#define SKIV_CLI_WINDOW_TITLE_HASH        SKIV_CLI_WINDOW_TITLE_SHORT_A SKIV_CLI_WINDOW_HASH

